### ISSUE TITLE
20180629 수업내용 정리

### ISSUE THREAD

**Issue by corazzon** [dataitgirls2/tutorial#3]
오전 통계 수업과 오후 헌법개정안으로 배우는 Git을 정리합니다.
통계와 Git을 나누어 2개의 마크다운 파일로 작성해 주시는 것을 권장합니다.
@oranjieunk @Dalbongjooin @DayoungHong @pje1740

**Comment by DayoungHong** [comment]
넵 알겠습니다!!
오늘안으로 완료하겠습니다.

이번주 수업 정말 감사드립니다!
다음주에 뵙겠습니다.

감사합니다 :)




2018년 7월 1일 (일) 오전 11:34, Joeun Park <notifications@github.com>님이 작성:

**Comment by corazzon** [comment]
내일까지 천천히 정리해 주셔도 됩니다. 즐거운 주말 보내세요 :)
